module.exports = {
  ESTIMATION: 'ESTIMATION',
  ESTIMATING_COST: 'ESTIMATING_COST',
  LOGIN: 'LOGIN',
  LOGIN_DEV: 'LOGIN_DEV',
  LOGGED_IN: 'LOGGED_IN',
  NEW_STATE: 'NEW_STATE',
  PUBLISH: 'PUBLISH',
  PUBLISHED: 'PUBLISHED',
  PUBLISHING: 'PUBLISHING',
  REGISTER: 'REGISTER',
  REGISTERED: 'REGISTERED',
  REGISTERING: 'REGISTERING'
}