#!/bin/bash

PROJECT_NAME=fm

files=$(find . -name "*.js" ! -path "./node_modules/*")

for f in ${files}; do
  debug="ara:${PROJECT_NAME}$(sed 's/\//\:/g' <<< $f | sed -r 's/\.(js)?//g')"

  #echo $debug
  sed -i -r "s/const debug = require\('debug'\)\('([A-Z]|[a-z]|\:)+'\)/const debug = require('debug')('${debug}')/g" $f
done
