
  name: ara-file-manager
  version: ''Publish, purchase, and download content on the Ara Network (https://ara.one) # 79 char long summary
  description: |
    The Ara File Manager is a simple desktop app that demonstrates the functionality of a
    complete local Ara network node and crypto token wallet. Ara is truly decentralized;
    with the Ara File Manager, your machine is participating directly in peer
    distribution swarms and the blockchain.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  
