name: ara-file-manager
version: 1.1.1
summary: Publish, purchase, and download content on the Ara Network (https://ara.one) # 79 char long summary
description: |
  The Ara File Manager is a simple desktop app that demonstrates the functionality of a
  complete local Ara network node and crypto token wallet. Ara is truly decentralized;
  with the Ara File Manager, your machine is participating directly in peer
  distribution swarms and the blockchain.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core ## ubuntu 16 (core18 is missing 'libfuse' at the moment)

architectures: [amd64, i386]

parts:
  ara-file-manager:
    plugin: dump
    source: https://github.com/AraBlocks/ara-file-manager/releases/download/$SNAPCRAFT_PROJECT_VERSION/Ara.File.Manager-$SNAPCRAFT_PROJECT_VERSION-linux.zip

apps:
  ara-file-manager:
    command: Ara\ File\ Manager-$SNAPCRAFT_PROJECT_VERSION.AppImage
    plugs:
      - alsa
      - audio-playback
      - avahi-control
      - avahi-observe
      - browser-support
      - desktop
      - desktop-legacy
      - fuse-support
      - hardware-random-observe
      - home
      - maliit
      - wayland
      - network
      - opengl
      - personal-files
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - upower-observe
      - x11
